# Generated by Django 6.0.4 on 2026-05-13 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='messages_thread__1ab240_idx',
            old_name='msg_thread_read_idx',
        ),
        migrations.RenameIndex(
            model_name='thread',
            new_name='message_thr_buyer_i_47dad1_idx',
            old_name='msg_thread_buyer_idx',
        ),
        migrations.RenameIndex(
            model_name='thread',
            new_name='message_thr_seller__4f615c_idx',
            old_name='msg_thread_seller_idx',
        ),
    ]
