# Generated by Django 6.0.4 on 2026-05-02 18:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FishListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('species', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_ssp', models.DecimalField(decimal_places=2, help_text='Price in SSP per unit', max_digits=12)),
                ('unit', models.CharField(choices=[('KG', 'Kilogram'), ('PIECE', 'Piece'), ('CRATE', 'Crate'), ('BUCKET', 'Bucket')], default='KG', max_length=10)),
                ('location', models.CharField(max_length=200)),
                ('photo_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('REMOVED', 'Removed')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fish_listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('IN_TRANSIT', 'In Transit'), ('CLEARED', 'Cleared'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='marketplace.fishlisting')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fishlisting',
            index=models.Index(fields=['status'], name='fish_listin_status_a6f725_idx'),
        ),
        migrations.AddIndex(
            model_name='fishlisting',
            index=models.Index(fields=['seller'], name='fish_listin_seller__b06fd1_idx'),
        ),
        migrations.AddIndex(
            model_name='fishlisting',
            index=models.Index(fields=['species'], name='fish_listin_species_5ec1e0_idx'),
        ),
        migrations.AddIndex(
            model_name='fishlisting',
            index=models.Index(fields=['location'], name='fish_listin_locatio_4311b7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_status_762191_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer'], name='orders_buyer_i_a41c52_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['listing'], name='orders_listing_310712_idx'),
        ),
    ]
