# Generated by Django 6.0.4 on 2026-05-06 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_fishlisting_coordinates_pricehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'seller_ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='pricehistory',
            new_name='price_histo_species_ca3c7f_idx',
            old_name='ph_species_time_idx',
        ),
        migrations.RenameIndex(
            model_name='pricehistory',
            new_name='price_histo_locatio_140e3b_idx',
            old_name='ph_location_time_idx',
        ),
        migrations.RemoveField(
            model_name='fishlisting',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='fishlisting',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='sellerrating',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerrating',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='marketplace.order'),
        ),
        migrations.AddField(
            model_name='sellerrating',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='sellerrating',
            constraint=models.CheckConstraint(condition=models.Q(('stars__gte', 1), ('stars__lte', 5)), name='stars_1_to_5'),
        ),
    ]
