# Generated by Django 6.0.4 on 2026-05-02 18:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorderClearance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checkpoint', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEARED', 'Cleared'), ('HELD', 'Held')], default='PENDING', max_length=8)),
                ('notes', models.TextField(blank=True, default='')),
                ('qr_code', models.TextField(blank=True, default='', help_text='Base64-encoded QR PNG')),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearances', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clearances', to='transport.shipment')),
            ],
            options={
                'db_table': 'border_clearances',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='border_clea_status_d9304d_idx'), models.Index(fields=['checkpoint'], name='border_clea_checkpo_ae0f0d_idx')],
            },
        ),
    ]
